### ISSUE TITLE
package.xml version was not bumped to latest version 1.4.0

### ISSUE THREAD

**Issue by cvina** [norlab-ulaval/libpointmatcher#549]
The latest version 1.4.0 was released recently, but the package.xml file still points to the previous version 1.3.1 

https://github.com/norlab-ulaval/libpointmatcher/blob/master/package.xml#L3

**Comment by RedLeader962** [comment]
Fixed in [PR 550](https://github.com/norlab-ulaval/libpointmatcher/pull/550)

Thanks for flagging it @cvina
