### ISSUE TITLE
degradation from challenging environment

### ISSUE THREAD

**Issue by iDonghq** [norlab-ulaval/libpointmatcher#584]
Could you tell me that the core of idea from "X-ICP: Localizability-Aware LiDAR Registration
for Robust Localization in Extreme Environments" is adopted by libpointmatcher?

**Comment by boxanm** [comment]
Hi @iDonghq, the work you mentioned isn't part of the main libpointmatcher's branch. I believe it was implemented in one of (possibly private) libpointmatcher's forks. I suggest you contact the paper's authors directly in case you have further questions about the method or the code.
