### ISSUE TITLE
C++ 17 and boost filesystem

### ISSUE THREAD

**Issue by sloriot** [norlab-ulaval/libpointmatcher#587]
Hi,

I see in some CMakeLists that you require c++17. If that's the case, would you accept a PR that replaces boost filesystem with the filesystem of the STL?

**Comment by boxanm** [comment]
Hello @sloriot and thanks for the offer!
We already replaced `boost::filesystem` in the `develop` branch, see this PR: https://github.com/norlab-ulaval/libpointmatcher/pull/581. There were some instabilities on our build server so it hasn't been merged to master yet. I believe they were fixed, so you can expect a new release of libpointmatcher later this week.

**Comment by sloriot** [comment]
Oh that's great, Thanks! I'll close the issue.

PS: I did try the `develop` branch @f42ea4ba7525646a9f2a2d723d341a2515fc6084 and it seems that something changed in the cmake magic. AFAIR, I could use it directly from the build dir but `${libpointmatcher_INCLUDE_DIRS}` only contains eigen path and not libpointmatcher include path. Trying `make install` does not help as it complains that it can't find `libpointmatcher-config.cmake` (wasn't copied most probably).
